config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :computations
  resources :tariffs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vodokanals 
    

  resources :watermeters do
    resources :watermeter_indications
  end
  root to: 'home#index'

  resources :watermeters 

  devise_for :accounts

   
  
end

app/models/watermeter.rb
class Watermeter < ApplicationRecord
  has_many :watermeter_indications
  has_many :watermeters, dependent: :destroy
  belongs_to :account
  belongs_to :vodokanal
  #belongs_to :tariff

  # validates :wm_name, presence: true, length: { maximum: 100 }
  # validates :wm_model, presence: true, length: { maximum: 10 }
  # validates :wm_factory_number, presence: true, uniqueness: true, length: { maximum: 10 }
  # validates :wm_diameter, presence: true, numericality: { only_integer: true }
  # validates :wm_address, presence: true,  length: { maximum: 500 }
  # validates :wm_make_date, presence: true
  # validates :wm_install_date, presence: true
  # validates :wm_stan, presence: true, numericality: { only_integer: true }
  # validates :wm_tu_number, presence: true, length: { maximum: 10 }
  # validates :wm_tu_date, presence: true
  # validates :wm_plomba_type, presence: true, numericality: { only_integer: true }
  # validates :wm_poverka_interval, presence: true, numericality: { only_integer: true }
  # validates :wm_poverka_last_date, presence: true
  # validates :wm_poverka_next_date, comparison: { greater_than: :wm_poverka_last_date }
  # validates :wm_name, presence: true

  def self.vodokanal_id
    Watermeter.first.vodokanal_id
  end

  def tariff_name
    Tariff.find(self.tariffs_id).name
  end

  def tariff_price
    Tariff.find(self.tariffs_id).price
  end

  

end

app/controllers/watermeters_controller.rb
class WatermetersController < ApplicationController
  before_action :set_watermeter, only: %i[ show edit update destroy ]
  before_action :authenticate_account!

  # GET /watermeters or /watermeters.json
  def index
    if account_signed_in?
      @watermeters = Watermeter.where(account_id: current_account.id).order('created_at ASC')
    else 
    end
  end

  # GET /watermeters/1 or /watermeters/1.json
  def show
    @watermeter = Watermeter.find(params[:id])
  end

  # GET /watermeters/new
  def new
    @watermeter = Watermeter.new
  end

  # GET /watermeters/1/edit
  def edit
  end

  # POST /watermeters or /watermeters.json
  def create
    @watermeter = Watermeter.new(watermeter_params)
    @watermeter.account_id = current_account.id
    @watermeter.vodokanal_id = "1"

    respond_to do |format|
      if @watermeter.save
        format.html { redirect_to @watermeter, notice: "Водомер успешно создан." }
        format.json { render :show, status: :created, location: @watermeter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @watermeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watermeters/1 or /watermeters/1.json
  def update
    respond_to do |format|
      if @watermeter.update(watermeter_params)
        format.html { redirect_to @watermeter, notice: "Информация о водомере успешно обновлена." }
        format.json { render :show, status: :ok, location: @watermeter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @watermeter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watermeters/1 or /watermeters/1.json
  def destroy
    @watermeter.destroy
    respond_to do |format|
      format.html { redirect_to watermeters_url, notice: "Водомер успешно удален" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watermeter
      @watermeter = Watermeter.where(account_id: current_account.id).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def watermeter_params
      params.require(:watermeter).permit(:wm_model, :wm_factory_number, :wm_diameter, :wm_address,\
         :wm_make_date, :wm_install_date, :wm_stan, :wm_tu_number, :wm_tu_date, :wm_plomba_type, \
         :wm_poverka_interval, :wm_poverka_last_date, :wm_poverka_next_date, :wm_control_check_date,\
          :wm_control_check_params, :wm_last_accept_report_date, :wm_last_accept_report_params,\
           :wm_last_sent_report_date, :wm_last_sent_report_params, :wm_last_sent_report_stan,\
           :wm_name, :wm_water_type, :wm_plomba_num, :wm_plomba_date, :vodokanal_id, :tariffs_id)
    end
end

app/helpers/watermeter_helper.rb
module WatermeterHelper
end

app/helpers/watermeters_helper.rb
module WatermetersHelper
end

app/views/watermeters/_form.html.erb
<div class="container">
 
    <div class="py-5 text-center">
      
      <h2>Карточка приладу обліку</h2>
      <p class="lead">Редагування інформації про прилад обліку ID <%= @watermeter.id %></p>
    </div>

   <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Останні показники</span>
          <span class="badge bg-primary rounded-pill"><%= @watermeter.wm_last_sent_report_params %></span>
        </h4>
        <ul class="list-group mb-3">
          
        </ul>
        
      </div>
        <div class="col-md-7 col-lg-8 ">
            <div class="common-form">
                       
                <div class="row">
                                    
                <%= form_with(model: watermeter, local: true) do |form| %>
                  <% if watermeter.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(watermeter.errors.count, "error") %> prohibited this watermeter from being saved:</h2>

                      <ul>
                        <% watermeter.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <h4 class="mb-3">Інформація про прилад</h4>

                  <div class="col-sm-12">
                    <%= form.label :tariffs_id, 'тариф', class: 'form-label' %>
                    <%= form.select :tariffs_id, options_for_select(Tariff.where(status: "1").all.map{|t| [t.name, t.id]}) %>
                  </div>
                
                  <div class="col-sm-12">
                    <%= form.label :wm_name, 'название водомера', class: 'form-label' %>
                    <%= form.text_field :wm_name, class: 'form-control' %>
                  </div>
                  
                  <div class="col-sm-6">
                        <%= form.label :wm_model, 'модель водомера', class: 'form-label' %>
                        <div class="input-group has-validation">
                          <span class="input-group-text">@</span>
                          <%= form.text_field :wm_model, class: 'form-control' %>
                        <div class="invalid-feedback">
                            Заповныть поле "модель".
                          </div>
                        </div>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_factory_number, 'заводской номер', class: 'form-label' %>
                    <div class="input-group has-validation">
                        <span class="input-group-text">@</span>
                        <%= form.text_field :wm_factory_number, class: 'form-control' %>
                        <div class="invalid-feedback">
                          Your username is required.
                        </div>
                    </div>
                  </div>

                  <div class="col-sm-4">
                    <%= form.label :wm_diameter, 'диаметр, мм', class: 'form-label' %>
                    <%= form.number_field :wm_diameter, class: 'form-control', in: 0.0..1000.0, step: 1 %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_address, 'адрес установки', class: 'form-label' %>
                    <%= form.text_field :wm_address, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_make_date, 'дата производства', class: 'form-label' %>
                    <%= form.date_select :wm_make_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_install_date, 'дата установки', class: 'form-label' %>
                    <%= form.date_select :wm_install_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_water_type, 'тип воды',class: 'form-label' %>
                    <%= form.select :wm_water_type, [["холодная","1"], ["горячая","2"]], class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_stan, 'состояние',class: 'form-label' %>
                    <%= form.select :wm_stan, [["новый","1"], ["бу","2"]], class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_tu_number, '№ ТУ', class: 'form-label' %>
                    <%= form.text_field :wm_tu_number, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_tu_date, 'дата ТУ',class: 'form-label' %>
                    <%= form.date_select :wm_tu_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_plomba_type, 'тип пломбы', class: 'form-label' %>
                    <%= form.select :wm_plomba_type, [["основная","1"], ["антимагнитная","2"], ["голограмма", "3"], ["пломбиратор","4"], ["дополнителная", "5"]],class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_plomba_num, '№ пломбы', class: 'form-label' %>
                    <%= form.text_field :wm_plomba_num, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_plomba_date, 'дата установки пломбы',class: 'form-label' %>
                    <%= form.date_select :wm_plomba_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_poverka_interval, 'интервал поверки',class: 'form-label' %>
                    <%= form.select :wm_poverka_interval,  [["6 месяцев","1"], ["12 месяцев","2"], ["24 месяца", "3"]], class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_poverka_last_date, 'дата последней поверки',class: 'form-label' %>
                    <%= form.date_select :wm_poverka_last_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_poverka_next_date, 'дата следующей поверки',class: 'form-label' %>
                    <%= form.date_select :wm_poverka_next_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_control_check_date, 'дата контр.показаний', class: 'form-label' %>
                    <%= form.date_select :wm_control_check_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_control_check_params, 'контр.показания',class: 'form-label' %>
                    <%= form.number_field :wm_control_check_params, class: 'form-control', in: 0.0..99999.0, step: 0.001 %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_last_accept_report_date, 'дата последних показаний которые принятые к расчету',class: 'form-label' %>
                    <%= form.date_select :wm_last_accept_report_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_last_accept_report_params, 'последние показания принятые к расчету',class: 'form-label' %>
                    <%= form.text_field :wm_last_accept_report_params, class: 'form-control', in: 0.0..99999.0, step: 0.001 %>
                  </div>

                  <div class="col-sm-12">
                    <%= form.label :wm_last_sent_report_date, 'дата последних  переданных показаний',class: 'form-label' %>
                    <%= form.date_select :wm_last_sent_report_date, class: 'form-control' %>
                  </div>

                  <div class="col-sm-6">
                    <%= form.label :wm_last_sent_report_params, 'последние переданные показания', class: 'form-label' %>
                    <%= form.text_field :wm_last_sent_report_params, class: 'form-control', in: 0.0..99999.0, step: 0.001 %>
                  </div>

                  <div class="col-sm-4">
                    <%= form.label :wm_last_sent_report_stan, 'последнее переданное состояние', class: 'form-label' %>
                    <%= form.select :wm_last_sent_report_stan, [["включен","1"], ["отключен","2"]],  class: 'form-control' %>
                  </div>

                  <div class="actions">
                    <%= form.submit class: 'w-100 btn btn-primary btn-lg' %>
                  </div>
                <% end %>

                </div>
          </div>
        </div>
    
    </div>

   

    </div>
 
</div>
 

app/views/watermeters/_rightdash.html.erb
<li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Product name</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$12</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Second product</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$8</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Third item</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$20</strong>
          </li>

app/views/watermeters/edit.html.erb
<%= render 'form', watermeter: @watermeter %>
<div class = "container">
<%= link_to 'Вернуться',   watermeters_path, class: 'w-500 btn btn-danger btn-lg'  %>
</div>

app/views/watermeters/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1>Приборы учета</h1>
  <%= link_to 'Добавить прибор', new_watermeter_path, class: 'btn btn-primary' %>

  <div class = "table-responsive">
    <table class = "table table-striped table-sm">
      <thead>
        <tr>
         <th>Id</th>
          <th>Модель</th>
          <th>Діаметр</th>
          <th>Адреса</th>
          <th>Стан</th>
          <th>Остання дата данних</th>
          <th>Останні данні</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @watermeters.each do |watermeter| %>
          <tr>
            <td><%= watermeter.id %></td>
            <td><%= watermeter.wm_model %></td>
            <td><%= watermeter.wm_diameter %></td>
            <td><%= watermeter.wm_address %></td>
            <td><%= watermeter.wm_stan %></td>
            <td><%= watermeter.wm_last_sent_report_date.strftime("%d.%m.%Y") %></td>
            <td><%= watermeter.wm_last_sent_report_params %></td>
            <td><%= link_to 'Просмотр паспорта', watermeter, class: 'btn btn-primary' %></td>
            <td><%= link_to 'Журнал показаний', watermeter_watermeter_indications_path(watermeter.id), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Передать показаня', new_watermeter_watermeter_indication_path(watermeter.id) , class: 'btn btn-primary' %></td>
            <td><%= link_to 'Редактировать', edit_watermeter_path(watermeter), class: 'btn btn-warning'  %></td>
            <td><%= link_to 'Удалить', watermeter, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Вы действительно хотите удалить устройство?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>

app/views/watermeters/new.html.erb
<div class="container-fluid">
<h1>Добавить новый прибор учета</h1>
<%= link_to 'Вернуться', watermeters_path, class: 'btn btn-primary' %>
<%= render 'form', watermeter: @watermeter %>
</div>

app/views/watermeters/show.html.erb
    <div class="container">
        <div class="row">
            <div class="col-lg-7 center-col">
                <div class="common-form">
                                
                <p id="notice"><%= notice %></p>
                <h2> Информация о тарифе </h2>
                <p>
                  <strong>Название тарифа :</strong>
                  <%= @watermeter.tariff_name %>
                </p>
                <p>
                  <strong>Цена тарифа (грн):</strong>
                  <%= @watermeter.tariff_price%>
                </p>
                <p>
                <h2> Информация о водомере </h2>
                <p>
                  <strong>Название водомера :</strong>
                  <%= @watermeter.wm_name %>
                </p>
                <p>
                  <strong>Модель водомера :</strong>
                  <%= @watermeter.wm_model %>
                </p>

                <p>
                  <strong>Заводской номер :</strong>
                  <%= @watermeter.wm_factory_number %>
                </p>

                <p>
                  <strong>Диаметр:</strong>
                  <%= @watermeter.wm_diameter %>
                </p>
                 <p>
                  <strong>Тип воды:</strong>
                  <%= @watermeter.wm_water_type %>
                </p>

                <p>
                  <strong>Адрес установки:</strong>
                  <%= @watermeter.wm_address %>
                </p>

                <p>
                  <strong>Дата производства:</strong>
                  <%= @watermeter.wm_make_date %>
                </p>

                <p>
                  <strong>Дата установки:</strong>
                  <%= @watermeter.wm_install_date %>
                </p>

                <p>
                  <strong>Состояние:</strong>
                  <%= @watermeter.wm_stan %>
                </p>

                <p>
                  <strong>№ техусловий:</strong>
                  <%= @watermeter.wm_tu_number %>
                </p>

                <p>
                  <strong>дата выдачи техусловия:</strong>
                  <%= @watermeter.wm_tu_date %>
                </p>

                <p>
                  <strong>тип пломбы:</strong>
                  <%= @watermeter.wm_plomba_type %>
                </p>

                <p>
                  <strong>номер пломбы:</strong>
                  <%= @watermeter.wm_plomba_num %>
                </p>

                <p>
                  <strong>дата установки пломбы:</strong>
                  <%= @watermeter.wm_plomba_date %>
                </p>


                <p>
                  <strong>интервал поверки:</strong>
                  <%= @watermeter.wm_poverka_interval %>
                </p>

                <p>
                  <strong>последняя дата поверки:</strong>
                  <%= @watermeter.wm_poverka_last_date %>
                </p>

                <p>
                  <strong>следующая дата поверки:</strong>
                  <%= @watermeter.wm_poverka_next_date %>
                </p>

                <p>
                  <strong>дата контрольных показаний:</strong>
                  <%= @watermeter.wm_control_check_date %>
                </p>

                <p>
                  <strong>контрольные показания:</strong>
                  <%= @watermeter.wm_control_check_params %>
                </p>

                <p>
                  <strong>дата последних показания принятые к расчету:</strong>
                  <%= @watermeter.wm_last_accept_report_date %>
                </p>

                <p>
                  <strong>последние показания принятые к расчету:</strong>
                  <%= @watermeter.wm_last_accept_report_params %>
                </p>

                <p>
                  <strong>дата последних переданых показаний:</strong>
                  <%= @watermeter.wm_last_sent_report_date %>
                </p>

                <p>
                  <strong>последние переданные показания:</strong>
                  <%= @watermeter.wm_last_sent_report_params %>
                </p>

                <p>
                  <strong>последнее переданное состояние:</strong>
                  <%= @watermeter.wm_last_sent_report_stan %>
                </p>
                <%= link_to 'Редактировать ', edit_watermeter_path(@watermeter), class: 'btn btn-primary' %> |
                <%= link_to 'Назад', watermeters_path, class: 'btn btn-dark' %>
            </div>
            </div>
        </div>
    </div>