config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :computations
  resources :tariffs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vodokanals 
    

  resources :watermeters do
    resources :watermeter_indications
  end
  root to: 'home#index'

  resources :watermeters 

  devise_for :accounts

   
  
end

app/models/computation.rb
class Computation < ApplicationRecord
  belongs_to :account
end

app/controllers/computations_controller.rb
class ComputationsController < ApplicationController
  before_action :set_computation, only: %i[ show edit update destroy ]

  # GET /computations or /computations.json
  def index
    @computations = Computation.all
  end

  # GET /computations/1 or /computations/1.json
  def show
  end

  # GET /computations/new
  def new
    @computation = Computation.new
  end

  # GET /computations/1/edit
  def edit
  end

  # POST /computations or /computations.json
  def create
    @computation = Computation.new(computation_params)

    respond_to do |format|
      if @computation.save
        format.html { redirect_to @computation, notice: "Computation was successfully created." }
        format.json { render :show, status: :created, location: @computation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computations/1 or /computations/1.json
  def update
    respond_to do |format|
      if @computation.update(computation_params)
        format.html { redirect_to @computation, notice: "Computation was successfully updated." }
        format.json { render :show, status: :ok, location: @computation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @computation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computations/1 or /computations/1.json
  def destroy
    @computation.destroy
    respond_to do |format|
      format.html { redirect_to computations_url, notice: "Computation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computation
      @computation = Computation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def computation_params
      params.require(:computation).permit(:name, :water_consumption, :price, :summa, :b_period, :e_period, :account_id, :watermeter_id, :tariff_id)
    end
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/views/computations/_form.html.erb
<section class="login">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 center-col">
                        <div class="common-form">
                            <h3>Новая транзакция</h3>
                              <%= form_with(model: computation, local: true) do |form| %>
                                <% if computation.errors.any? %>
                                  <div id="error_explanation">
                                    <h2><%= pluralize(computation.errors.count, "error") %> prohibited this computation from being saved:</h2>

                                    <ul>
                                      <% computation.errors.full_messages.each do |message| %>
                                        <li><%= message %></li>
                                      <% end %>
                                    </ul>
                                  </div>
                                <% end %>
                                <div class="row">
                                    <div class="col-md-12 margin-15px-bottom">
                                         <%= form.label :name %>
                                         <%= form.text_field :name %>
                                    </div>
                                    <div class="col-12 margin-15px-bottom">
                                         <%= form.label :water_consumption %>
                                         <%= form.text_field :water_consumption %>
                                    </div>
                                    <div class="col-12 margin-20px-bottom">
                                         <%= form.label :price %>
                                         <%= form.text_field :price %>
                                    </div>
                                     <div class="col-12 margin-20px-bottom">
                                         <%= form.label :summa %>
                                         <%= form.text_field :summa %>
                                     </div>
                                     <div class="col-12 margin-20px-bottom">
                                      <%= form.label :b_period %>
                                      <%= form.date_select :b_period %>
                                     </div>
                                     <div class="col-12 margin-20px-bottom">
                                      <%= form.label :e_period %>
                                      <%= form.date_select :e_period %>
                                     </div>
                                     <div class="col-12 margin-20px-bottom">
                                      <%= form.label :account_id %>
                                      <%= form.text_field :account_id %>
                                     </div>
                                      <div class="col-12 margin-20px-bottom">
                                      <%= form.label :watermeter_id %>
                                      <%= form.text_field :watermeter_id %>
                                     </div>
                                      <div class="col-12 margin-20px-bottom">
                                      <%= form.label :tariff_id %>
                                      <%= form.text_field :tariff_id %>
                                     </div>


                                    <div class="col-12">
                                        <%= form.submit class: 'butn theme medium' %>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>

            </div>
        </section>




  <div class="actions">
   
  </div>

app/views/computations/edit.html.erb
<h1>Editing Computation</h1>

<%= render 'form', computation: @computation %>

<%= link_to 'Show', @computation %> |
<%= link_to 'Back', computations_path %>

app/views/computations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
<h1>Расчеты</h1>
<%= link_to 'Создать новый расчет', new_computation_path, class: 'btn btn-primary' %>
<table class = "table table-striped table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>Water consumption</th>
      <th>Price</th>
      <th>Summa</th>
      <th>B period</th>
      <th>E period</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computations.each do |computation| %>
      <tr>
        <td><%= computation.name %></td>
        <td><%= computation.water_consumption %></td>
        <td><%= computation.price %></td>
        <td><%= computation.summa %></td>
        <td><%= computation.b_period %></td>
        <td><%= computation.e_period %></td>
        <td><%= computation.account_id %></td>
        <td><%= link_to 'Show', computation %></td>
        <td><%= link_to 'Edit', edit_computation_path(computation) %></td>
        <td><%= link_to 'Destroy', computation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/computations/new.html.erb
<%= render 'form', computation: @computation %>

<%= link_to 'Back', computations_path %>

app/views/computations/show.html.erb
    <div class="container">
        <div class="row">
            <div class="col-lg-7 center-col">
                <div class="common-form">
                <p id="notice"><%= notice %></p>

            <p>
              <strong>Name:</strong>
              <%= @computation.name %>
            </p>

            <p>
              <strong>Water consumption:</strong>
              <%= @computation.water_consumption %>
            </p>

            <p>
              <strong>Price:</strong>
              <%= @computation.price %>
            </p>

            <p>
              <strong>Summa:</strong>
              <%= @computation.summa %>
            </p>

            <p>
              <strong>B period:</strong>
              <%= @computation.b_period %>
            </p>

            <p>
              <strong>E period:</strong>
              <%= @computation.e_period %>
            </p>

            <p>
              <strong>Account:</strong>
              <%= @computation.account_id %>
            </p>

            <%= link_to 'Edit', edit_computation_path(@computation) %> |
            <%= link_to 'Back', computations_path %>
            </div>
            </div>
        </div>
    </div>