config/routes.rb
Rails.application.routes.draw do
  
  resources :payments
  resources :computations
  resources :tariffs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vodokanals 
    

  resources :watermeters do
    resources :watermeter_indications
  end
  root to: 'home#index'

  resources :watermeters 

  devise_for :accounts

   
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :watermeters, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computation.rb
class Computation < ApplicationRecord
  belongs_to :account
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :computation
  belongs_to :account
  belongs_to :vodokanal
end

app/models/tariff.rb
class Tariff < ApplicationRecord
    has_many :watermeters
end

app/models/vodokanal.rb
class Vodokanal < ApplicationRecord
    has_many :vodokanal_props, dependent: :destroy
    has_many :watermeters, dependent: :destroy

    def self.vodokanal_full_name
        Vodokanal.first.full_name
    end

    def self.vodokanal_address
        Vodokanal.first.address
    end

    def self.vodokanal_email
        Vodokanal.first.email
    end

    def self.vodokanal_tel_1
        Vodokanal.first.tel_1
    end

    def self.vodokanal_tel_2
        Vodokanal.first.tel_2
    end

    def self.vodokanal_tel_3
        Vodokanal.first.tel_3
    end

    def self.vodokanal_director
        Vodokanal.first.director
    end

    def self.vodokanal_acounter
        Vodokanal.first.acounter
    end

    def self.vodokanal_description
        Vodokanal.first.description
    end
end

app/models/vodokanal_prop.rb
class VodokanalProp < ApplicationRecord
  belongs_to :vodokanal
end

app/models/watermeter.rb
class Watermeter < ApplicationRecord
  has_many :watermeter_indications
  has_many :watermeters, dependent: :destroy
  belongs_to :account
  belongs_to :vodokanal
  #belongs_to :tariff

  # validates :wm_name, presence: true, length: { maximum: 100 }
  # validates :wm_model, presence: true, length: { maximum: 10 }
  # validates :wm_factory_number, presence: true, uniqueness: true, length: { maximum: 10 }
  # validates :wm_diameter, presence: true, numericality: { only_integer: true }
  # validates :wm_address, presence: true,  length: { maximum: 500 }
  # validates :wm_make_date, presence: true
  # validates :wm_install_date, presence: true
  # validates :wm_stan, presence: true, numericality: { only_integer: true }
  # validates :wm_tu_number, presence: true, length: { maximum: 10 }
  # validates :wm_tu_date, presence: true
  # validates :wm_plomba_type, presence: true, numericality: { only_integer: true }
  # validates :wm_poverka_interval, presence: true, numericality: { only_integer: true }
  # validates :wm_poverka_last_date, presence: true
  # validates :wm_poverka_next_date, comparison: { greater_than: :wm_poverka_last_date }
  # validates :wm_name, presence: true

  def self.vodokanal_id
    Watermeter.first.vodokanal_id
  end

  def tariff_name
    Tariff.find(self.tariffs_id).name
  end

  def tariff_price
    Tariff.find(self.tariffs_id).price
  end

  

end

app/models/watermeter_indication.rb
class WatermeterIndication < ApplicationRecord
  belongs_to :watermeter
  validates :data, :numericality =>{:greater_than => 0}
  validate :data_cannot_be_less_than_last_value
  
  def data_cannot_be_less_than_last_value

    @watermeter = Watermeter.find(watermeter.id)

    if @watermeter.wm_last_sent_report_params > self.data
      errors.add(:data,  'Переданые данные ошибочны. Показания меньше предыдущих.') 
    end
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tariffs_helper.rb
module TariffsHelper
end

app/helpers/vodokanals_helper.rb
module VodokanalsHelper
end

app/helpers/watermeter_helper.rb
module WatermeterHelper
end

app/helpers/watermeters_helper.rb
module WatermetersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Водоканал - система учета</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag asset_path('img/logos/apple-touch-icon-57x57.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  
  </head>
   

    
  <body>
  <header>
    <% if account_signed_in? %>
    <%= render "layouts/nav/topmenu"%>
    <% else %>
    <%= render "layouts/nav/topmenu"%>
    <% end %>
    </header> 

      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <%= yield %>
  
    <%= render "layouts/nav/footer"%>
    <%= javascript_pack_tag 'main' %>
    <%= javascript_pack_tag 'core_min' %>
  </body>
</html>

app/views/layouts/nav/_footer.html.erb
         <!-- start footer section -->
        <footer>
            <div class="container">
                <div class="row margin-30px-bottom padding-30px-bottom border-bottom border-color-light-white">

                    <div class="col-lg-4 col-md-12 sm-margin-30px-bottom text-center">

                        <h3 class="footer-title-style text-white">Телефони</h3>
                        <p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_tel_1 %></p>
			<p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_tel_2 %></p>
			<p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_tel_3 %></p>
                    </div>

                    <div class="col-lg-4 col-md-12 sm-margin-30px-bottom text-center">
                        <h3 class="footer-title-style text-white">Email</h3>
                        <p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_email %></p>
                    </div>

                    <div class="col-lg-4 col-md-12 text-center">
                        <h3 class="footer-title-style text-white">Адреса</h3>
                        <p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_full_name %></p>
                        <p class="font-size16 sm-font-size14"><%= Vodokanal.vodokanal_address %></p>
                    </div>

                </div>

                <div class="row">
                    <div class="col-12 text-center">
                        <ul class="social-icon-style2 no-margin">
                           
                            <li>
                               <%= fa_icon "camera-retro" %>
                            </li>
                            <li>
                              <%= fa_icon "camera-retro" %>
                            </li>
                            <li>
                              <%= fa_icon "camera-retro" %>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            <div class="footer-bar">
                <div class="container">
                    <p class="xs-font-size13">&copy; 2021 ПОГ "НВП Проминь"</p>
                </div>
            </div>
        </footer>
        <!-- end footer section -->
        
        
   </div>
    <!-- end main-wrapper section -->

   

    <!-- start scroll to top -->
    <a href="javascript:void(0)" class="scroll-to-top"><i class="fas fa-angle-up" aria-hidden="true"></i></a>
    <!-- end scroll to top -->

 

app/views/layouts/nav/_langauge.html.erb
<li><%= link_to 'English', root_path(locale: :en) %></li>
<li><%= link_to 'Русский', root_path(locale: :ru) %></li>

app/views/layouts/nav/_top_lk_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Водоканал</a>
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarCollapse" style="">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
            
        <li class="nav-item">
        <%= link_to 'Главная', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <% if account_signed_in? %>
                <li> <%= link_to 'Выход', destroy_account_session_path, method: :delete, class: 'nav-link active' %> </li>
            <% else %>
                <li> <%= link_to 'Вход', new_account_session_path, class: 'nav-link active' %> </li>
            <% end %>
        </li>
      </ul>
     
    </div>
  </div>
</nav>

app/views/layouts/nav/_topmenu.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Водоканал</a>
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarCollapse" style="">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
        <%= link_to 'Главная', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <% if account_signed_in? %>
                <li> <%= link_to 'Приборы учета', watermeters_path, class: 'nav-link active' %> </li>
                <li> <%= link_to 'Расчеты', computations_path, class: 'nav-link active' %> </li>
                <li> <%= link_to 'Тарифы', tariffs_path, class: 'nav-link active' %> </li>
                <li> <%= link_to 'Оплата',  payments_path, class: 'nav-link active' %> </li>
                <li> <%= link_to 'Аккаунт', edit_account_registration_path,  class: 'nav-link active' %> </li>
                <li> <%= link_to 'Выход', destroy_account_session_path, method: :delete, class: 'nav-link active' %> </li>
            <% else %>
                <li> <%= link_to 'Вход', new_account_session_path, class: 'nav-link active' %> </li>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>